trigger:
  tags:
    include:
    - v*
  branches:
    exclude:
    - master
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g vsce
  displayName: 'npm install and vsce'
 
- task: CmdLine@1
  displayName: 'Run vsce package'
  inputs:
    filename: 'vsce '
    arguments: package
    workingFolder: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  inputs:
    contents: '**/*.vsix'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
   PathtoPublish: $(Build.ArtifactStagingDirectory)
   publishLocation: Container
   TargetPath: '**/*.vsix'
   artifactName: 'VSIX'
